[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
net = { path ="../net"}
async-trait = "0.1.64"
tokio = { version = "1.25.0", features = ["full"] }
thiserror = "1.0.38"